apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 068264331860.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:22dcfb969924c5ecc915deb6473aa51fdff584eb
        ports:
        - containerPort: 80
