apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 211125319040.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:6d55852854fc4e0a3615f2576d1b63dd2a416ec8
        ports:
        - containerPort: 80
