apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 068264331860.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:22dcfb969924c5ecc915deb6473aa51fdff584eb
        ports:
        - containerPort: 80
