apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 556930053779.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:2b4f46b6f8bcb922acbb84513244a3b944646648
        ports:
        - containerPort: 80
