apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 211125319040.dkr.ecr.us-west-2.amazonaws.com/shopping-site-main:6d55852854fc4e0a3615f2576d1b63dd2a416ec8
        ports:
        - containerPort: 80

