apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 211125319040.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:5c96b67a3321977bb9f22a041c227477b1f3aa7f
        ports:
        - containerPort: 80
