apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 068264331860.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:22dcfb969924c5ecc915deb6473aa51fdff584eb
        ports:
        - containerPort: 80
