apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 556930053779.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:2b4f46b6f8bcb922acbb84513244a3b944646648
        ports:
        - containerPort: 80
