apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 211125319040.dkr.ecr.us-west-2.amazonaws.com/shopping-site-computers:5c96b67a3321977bb9f22a041c227477b1f3aa7f
        ports:
        - containerPort: 80
