apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 068264331860.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:7abfe153fd3e5dcc82e46d6859a7921b87eaea31
        ports:
        - containerPort: 80
